---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: false

env:
  - ANSIBLE_VERSION=git

branches:
  only:
    - master

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; elif [ "$ANSIBLE_VERSION" = "git" ]; then pip install git+https://github.com/ansible/ansible.git ; else pip install ansible==$ANSIBLE_VERSION; fi
  - pip install ansible-lint

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook tests/test_travis.yml -i tests/inventory --syntax-check
  - ansible-lint tests/test_travis.yml

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
